### ISSUE TITLE
celnav.ini doens't get installed to $HOME/.celnav

### ISSUE THREAD

**Issue by ghost** [ms8r/celnav#2]
```
Traceback (most recent call last):
  File "/opt/celnav/cnscript.py", line 7, in <module>
    import celnav.cnapp as cc
  File "/usr/lib/python2.7/site-packages/celnav/cnapp.py", line 34, in <module>
    import celnav
  File "/usr/lib/python2.7/site-packages/celnav/celnav.py", line 35, in <module>
    import starcat
  File "/usr/lib/python2.7/site-packages/celnav/starcat.py", line 127, in <module>
    import cncfg
  File "/usr/lib/python2.7/site-packages/celnav/cncfg.py", line 31, in <module>
    build_cfg()
  File "/usr/lib/python2.7/site-packages/celnav/cncfg.py", line 27, in build_cfg
    warningStr = "Could not read configuration file %s" % INI_PATH
NameError: global name 'INI_PATH' is not defined
```

A manual copy fixes this but install.py needs to be edited.

**Comment by ms8r** [comment]
Thanks. `setup.py` was erroneously creating the application directory under `/root` when run with `sudo`. Fixed with 95e4a72. You may want to delete `/root/.celnav` which was probably created during your install.

`INI_PATH` error above also fixed in  95e4a72.
