### ISSUE TITLE
Setup Error on Windows and pycharm

### ISSUE THREAD

**Issue by masoudline** [ms8r/celnav#3]
hi
i am using windows 10 os and i want run your code but below error occur:
Traceback (most recent call last):
  File "D:/Military/setup.py", line 21, in <module>
    APP_DIR = os.path.join('/home', user, '.celnav')   # used for ini, cfg files
  File "C:\Python27\lib\ntpath.py", line 67, in join
    p_drive, p_path = splitdrive(p)
  File "C:\Python27\lib\ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()

thanks for your reply

**Comment by masoudline** [comment]
no any body here?

**Comment by ms8r** [comment]
Hi - Sorry but I don't have access to a WIndows machine and so far Celnav has only been maintained for Linux / MacOS type platforms.  If you just want to take it for a spin, the easiest might be to download [Navigatrix](http://navigatrix.net) which comes packaged with [Celnav included](http://navigatrix.net/viewtopic.php?f=21&t=423). Navigatrix is a lightweight Linux distribution that bundles a bunch of navigation software for cruisers. You can run Navigatrix from a USB stick on x86 WIndows machines without having to install anything.  Instructions can be found here: http://navigatrix.net/download.php .

Good luck!

**Comment by masoudline** [comment]
can I use the camera for detect Polaris star with your code project?
